/**
 * Generates a real, downloadable PDF in the browser (no dependencies).
 * Draws the book's gradient cover with title, then sample content pages.
 * Persian text is rendered via embedded font substitution: since drawing
 * shaped Arabic-script text requires a full font, the PDF content pages
 * use transliterated metadata + layout chrome, and the full book is
 * represented by generated chapter placeholder pages.
 */

type PdfBook = {
  title: string;
  author: string;
  category: string;
  pages: number;
  coverFrom: number;
  coverTo: number;
};

// Minimal PDF building blocks ------------------------------------------------

function pdfEscape(text: string): string {
  return text.replace(/\\/g, "\\\\").replace(/\(/g, "\\(").replace(/\)/g, "\\)");
}

function buildContentStream(ops: string[]): string {
  return ops.join("\n");
}

function latinize(s: string): string {
  // WinAnsi-safe approximation: strip non-latin chars for body text.
  return s.replace(/[^\x20-\x7E]/g, "");
}

export function generateBookPdf(
  book: PdfBook,
  ownerLabel: string,
  trackingCode: string,
): Blob {
  const objs: string[] = [];

  const addObj = (body: string) => {
    objs.push(body);
    return objs.length; // 1-based object numbers
  };

  // Colors from hue
  const c1 = hslToRgb01(book.coverFrom, 0.72, 0.55);
  const c2 = hslToRgb01(book.coverTo, 0.72, 0.45);

  // ---- Page geometry ----
  const W = 595; // A4 width pt
  const H = 842; // A4 height pt

  const pages: string[][] = [];

  // ---- Cover page ----
  pages.push([
    "q",
    `${c1[0]} ${c1[1]} ${c1[2]} rg`,
    `0 0 ${W} ${H} re f`,
    `${c2[0]} ${c2[1]} ${c2[2]} rg`,
    `0 0 ${W} 620 re f`,
    "0.95 0.95 0.98 rg",
    "BT /F2 40 Tf 60 700 Td (PDFStore) Tj ET",
    "0.85 0.86 0.95 rg",
    "BT /F2 16 Tf 60 670 Td (Persian Digital Library) Tj ET",
    "1 1 1 rg",
    `BT /F2 30 Tf 60 380 Td (${pdfEscape(latinize(book.title))}) Tj ET`,
    "0.9 0.9 0.95 rg",
    `BT /F2 14 Tf 60 350 Td (by ${pdfEscape(latinize(book.author))}) Tj ET`,
    `BT /F2 12 Tf 60 330 Td (${pdfEscape(latinize(book.category))} - ${book.pages} pages) Tj ET`,
    "0.7 0.7 0.8 rg",
    `BT /F1 10 Tf 60 60 Td (Licensed to: ${pdfEscape(latinize(ownerLabel))}) Tj ET`,
    `BT /F1 10 Tf 60 46 Td (Order: ${pdfEscape(trackingCode)}) Tj ET`,
    "Q",
  ]);

  // ---- Info page ----
  pages.push([
    "0.1 0.1 0.15 rg",
    "BT /F2 22 Tf 60 780 Td (About this edition) Tj ET",
    "0.3 0.3 0.4 rg",
    `BT /F1 11 Tf 60 740 Td (Title: ${pdfEscape(latinize(book.title))}) Tj ET`,
    `BT /F1 11 Tf 60 720 Td (Author: ${pdfEscape(latinize(book.author))}) Tj ET`,
    `BT /F1 11 Tf 60 700 Td (Category: ${pdfEscape(latinize(book.category))}) Tj ET`,
    `BT /F1 11 Tf 60 680 Td (Pages: ${book.pages}) Tj ET`,
    "0.15 0.15 0.2 rg",
    "BT /F1 11 Tf 60 620 Td (This is a demo copy generated by PDFStore.) Tj ET",
    "BT /F1 11 Tf 60 600 Td (The full Persian text is available in the printed edition.) Tj ET",
  ]);

  // ---- Sample chapter pages ----
  const chapters = ["Chapter 1", "Chapter 2", "Chapter 3", "Chapter 4"];
  for (let i = 0; i < chapters.length; i++) {
    const y = 760;
    pages.push([
      "0.1 0.1 0.15 rg",
      `BT /F2 20 Tf 60 ${y} Td (${chapters[i]}) Tj ET`,
      "0.4 0.4 0.5 rg",
      ...Array.from({ length: 16 }, (_, line) =>
        `BT /F1 11 Tf 60 ${y - 40 - line * 22} Td (${pdfEscape(
          latinize(
            `Sample line ${line + 1} of chapter ${i + 1} — placeholder text of the PDFStore demo edition.`,
          ),
        )}) Tj ET`,
      ),
    ]);
  }

  // ---- Assemble PDF objects ----
  const fontRegular = addObj("<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>");
  const fontBold = addObj("<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>");

  const pageCount = pages.length;
  const kids: number[] = [];
  const pageObjNums: number[] = [];

  const pagesNodeNum = objs.length + pageCount * 2 + 1; // computed after; we allocate sequentially instead

  // Allocate in order: for each page: content obj, page obj
  let pagesNode: number | null = null;
  // Reserve the Pages node object number: it will be allocated after content/page objs
  const startObjNum = objs.length + 1;
  const pagesNodeNumFinal = startObjNum + pageCount * 2;
  pagesNode = pagesNodeNumFinal;

  for (const ops of pages) {
    const stream = buildContentStream(ops);
    const contentNum = addObj(
      `<< /Length ${stream.length} >>\nstream\n${stream}\nendstream`,
    );
    const pageNum = addObj(
      `<< /Type /Page /Parent ${pagesNode} 0 R /MediaBox [0 0 ${W} ${H}] ` +
        `/Resources << /Font << /F1 ${fontRegular} 0 R /F2 ${fontBold} 0 R >> >> ` +
        `/Contents ${contentNum} 0 R >>`,
    );
    pageObjNums.push(pageNum);
  }

  pagesNode = addObj(
    `<< /Type /Pages /Kids [${pageObjNums.map((n) => `${n} 0 R`).join(" ")}] /Count ${pageCount} >>`,
  );
  void pagesNodeNum; // legacy computation kept for clarity

  const catalogNum = addObj(
    `<< /Type /Catalog /Pages ${pagesNode} 0 R >>`,
  );

  const encoder = new TextEncoder();
  const header = "%PDF-1.4\n%\xE2\xE3\xCF\xD3\n";
  const headerBytes = encoder.encode(header);

  const chunks: Uint8Array[] = [headerBytes];
  const offsets: number[] = [];
  let offset = headerBytes.length;

  for (let i = 0; i < objs.length; i++) {
    const objStr = `${i + 1} 0 obj\n${objs[i]}\nendobj\n`;
    const bytes = encoder.encode(objStr);
    offsets.push(offset);
    chunks.push(bytes);
    offset += bytes.length;
  }

  const xrefStart = offset;
  const xref =
    `xref\n0 ${objs.length + 1}\n` +
    `0000000000 65535 f \n` +
    offsets.map((o) => `${String(o).padStart(10, "0")} 00000 n \n`).join("");
  const xrefBytes = encoder.encode(xref);
  chunks.push(xrefBytes);
  offset += xrefBytes.length;

  const trailer =
    `trailer\n<< /Size ${objs.length + 1} /Root ${catalogNum} 0 R >>\nstartxref\n${xrefStart}\n%%EOF\n`;
  chunks.push(encoder.encode(trailer));

  const total = chunks.reduce((s, c) => s + c.length, 0);
  const out = new Uint8Array(total);
  let pos = 0;
  for (const c of chunks) {
    out.set(c, pos);
    pos += c.length;
  }
  return new Blob([out], { type: "application/pdf" });
}

function hslToRgb01(h: number, s: number, l: number): [number, number, number] {
  const hn = ((h % 360) + 360) % 360 / 360;
  const f = (n: number) => {
    const k = (n + hn * 12) % 12;
    const a = s * Math.min(l, 1 - l);
    return l - a * Math.max(-1, Math.min(k - 3, 9 - k, 1));
  };
  return [round(f(0)), round(f(8)), round(f(4))];
}

function round(x: number): number {
  return Math.round(x * 1000) / 1000;
}

/** Trigger a browser download of a generated Blob. */
export function downloadBlob(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  a.remove();
  setTimeout(() => URL.revokeObjectURL(url), 4000);
}
